=== infsci2560sp16/full-stack-web-project-mes250/src/main/resources/public/inventory.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://stark-earth-7570.herokuapp.com/schema/inventory" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="inventory">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="device" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="inv_id"/>
              <xs:element type="xs:string" name="owner"/>
              <xs:element type="xs:string" name="device_name"/>
              <xs:element type="xs:string" name="manufacturer"/>
              <xs:element type="xs:string" name="model"/>
              <xs:element type="xs:byte" name="type"/>
              <xs:element type="xs:string" name="ip_address"/>
              <xs:element type="xs:string" name="serial"/>
              <xs:element type="xs:string" name="processor"/>
              <xs:element type="xs:byte" name="ram"/>
              <xs:element type="xs:string" name="location"/>
              <xs:element type="xs:byte" name="type_id"/>
              <xs:element type="xs:string" name="type_desc"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== infsci2560sp16/full-stack-web-project-mes250/src/main/resources/public/inventoryXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<inventory xmlns="http://stark-earth-7570.herokuapp.com/schema/inventory" 
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xsi:schemaLocation="http://stark-earth-7570.herokuapp.com/schema/inventory file:/Users/mike/Web/GitHub/full-stack-web-project-mes250/src/main/resources/public/inventory.xsd">
<device>
<inv_id>1</inv_id>
<owner>Andrea Durst</owner>
<device_name>HGEN-LT-133</device_name>
<manufacturer>Dell</manufacturer>
<model>Lattitude E6540</model>
<type>2</type>
<ip_address>192.168.0.1</ip_address>
<serial>JTZGD12</serial>
<processor>Intel Core i7-4800MQ 2.70GHz</processor>
<ram>16</ram>
<location>A305</location>
<type_id>2</type_id>
<type_desc>Laptop</type_desc>
</device>
<device>
<inv_id>2</inv_id>
<owner>Andrea Durst</owner>
<device_name>HGEN-LT-Durst</device_name>
<manufacturer>Microsoft</manufacturer>
<model>Surface Pro 3</model>
<type>2</type>
<ip_address>192.168.0.2</ip_address>
<serial>33015251353</serial>
<processor>Intel Core i5 2.7 GHz</processor>
<ram>8</ram>
<location>A305</location>
<type_id>2</type_id>
<type_desc>Laptop</type_desc>
</device>
<device>
<inv_id>3</inv_id>
<owner>Angel Daily</owner>
<device_name>norbut</device_name>
<manufacturer>Dell</manufacturer>
<model>OptiPlex 7010</model>
<type>1</type>
<ip_address>192.168.0.3</ip_address>
<serial>CNNPNW1</serial>
<processor>Intel Core i7-3770 3.40GHz</processor>
<ram>6</ram>
<location>A306</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>4</inv_id>
<owner>Angel Daily</owner>
<device_name>HGEN-WKS-194</device_name>
<manufacturer>Dell</manufacturer>
<model>OptiPlex 980</model>
<type>1</type>
<ip_address>192.168.0.4</ip_address>
<serial>BX8PDQ1</serial>
<processor>Intel Core i7 870 2.93GHz</processor>
<ram>8</ram>
<location>A309</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>5</inv_id>
<owner>Beth Roman</owner>
<device_name>default</device_name>
<manufacturer>Apple</manufacturer>
<model>iMac</model>
<type>1</type>
<ip_address>192.168.0.5</ip_address>
<serial>123456789</serial>
<processor>Intel Core i5 2.7 GHz</processor>
<ram>8</ram>
<location>A309</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>6</inv_id>
<owner>Beth Roman</owner>
<device_name>HGEN-RLab-2</device_name>
<manufacturer>Apple</manufacturer>
<model>iMac</model>
<type>1</type>
<ip_address>192.168.0.6</ip_address>
<serial>YM0230R3DMV</serial>
<processor>Intel Core i5 2.7 GHz</processor>
<ram>8</ram>
<location>A300</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>7</inv_id>
<owner>Beth Roman</owner>
<device_name>romanpc</device_name>
<manufacturer>Dell</manufacturer>
<model>Precision T1600</model>
<type>1</type>
<ip_address>192.168.0.7</ip_address>
<serial>DGVFLS1</serial>
<processor>Intel Xeon E31205</processor>
<ram>16</ram>
<location>A300</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>8</inv_id>
<owner>Beth Roman</owner>
<device_name>default</device_name>
<manufacturer>Dell</manufacturer>
<model>Dimension E520</model>
<type>1</type>
<ip_address>192.168.0.8</ip_address>
<serial>9X16DC1</serial>
<processor>Intel Pentium 4 3.20GHz</processor>
<ram>2</ram>
<location>A300</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>9</inv_id>
<owner>Beth Roman</owner>
<device_name>default</device_name>
<manufacturer>Lexmark</manufacturer>
<model>Lexmark MS310dn</model>
<type>8</type>
<ip_address>192.168.0.9</ip_address>
<serial>451432LM0WRW7-98-0</serial>
<processor>Intel Core i5 2.7 GHz</processor>
<ram>128</ram>
<location>3rd FLR Annex</location>
<type_id>8</type_id>
<type_desc>Printer</type_desc>
</device>
<device>
<inv_id>10</inv_id>
<owner>Betsy Gettig</owner>
<device_name>default</device_name>
<manufacturer>Apple</manufacturer>
<model>MacBook Pro</model>
<type>2</type>
<ip_address>192.168.0.10</ip_address>
<serial>C02M21AGFD58</serial>
<processor>Intel Core i5 2.7 GHz</processor>
<ram>8</ram>
<location>A300</location>
<type_id>2</type_id>
<type_desc>Laptop</type_desc>
</device>
<device>
<inv_id>11</inv_id>
<owner>Candace Kammerer</owner>
<device_name>HGEN-Candy2</device_name>
<manufacturer>Apple</manufacturer>
<model>iMac</model>
<type>1</type>
<ip_address>192.168.0.11</ip_address>
<serial>D25L90Y0DNMP</serial>
<processor>Intel Core i7 3.4 GHz</processor>
<ram>16</ram>
<location>619</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>12</inv_id>
<owner>Candace Kammerer</owner>
<device_name/>
<manufacturer>Apple</manufacturer>
<model>MacBook Air</model>
<type>2</type>
<ip_address>192.168.0.12</ip_address>
<serial>123456789</serial>
<processor>Intel Core i5 2.7 GHz</processor>
<ram>8</ram>
<location>A300</location>
<type_id>2</type_id>
<type_desc>Laptop</type_desc>
</device>
<device>
<inv_id>13</inv_id>
<owner>Dan Weeks</owner>
<device_name>thymine</device_name>
<manufacturer>Apple</manufacturer>
<model>Mac Mini</model>
<type>1</type>
<ip_address>192.168.0.13</ip_address>
<serial>D49A20DE1EBC</serial>
<processor>Intel Core i7 3.4 GHz</processor>
<ram>8</ram>
<location>614</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>14</inv_id>
<owner>Dan Weeks</owner>
<device_name>basesequence</device_name>
<manufacturer>Apple</manufacturer>
<model>iMac</model>
<type>1</type>
<ip_address>192.168.0.14</ip_address>
<serial>D25JF0Y8DHJW</serial>
<processor>Intel Core i7 3.4 GHz</processor>
<ram>16</ram>
<location>4000 Cube</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>15</inv_id>
<owner>Dan Weeks</owner>
<device_name>apple-time-caps</device_name>
<manufacturer>Apple</manufacturer>
<model>Time Capsule</model>
<type>5</type>
<ip_address>192.168.0.15</ip_address>
<serial>123456789</serial>
<processor>Intel Core i7 3.4 GHz</processor>
<ram/>
<location>A725</location>
<type_id>5</type_id>
<type_desc>Physical Server</type_desc>
</device>
<device>
<inv_id>16</inv_id>
<owner>Dan Weeks</owner>
<device_name>Sherlock</device_name>
<manufacturer>Apple</manufacturer>
<model>Mac Pro</model>
<type>1</type>
<ip_address>192.168.0.16</ip_address>
<serial>C07KJ06PF4MH</serial>
<processor>6-Core Intel Xeon 3.06 GHz</processor>
<ram>32</ram>
<location>A303</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>17</inv_id>
<owner>Dan Weeks</owner>
<device_name>penrose</device_name>
<manufacturer>Apple</manufacturer>
<model>Mac Pro</model>
<type>1</type>
<ip_address>192.168.0.17</ip_address>
<serial>1F5B325421</serial>
<processor>Intel Core i7 3.4 GHz</processor>
<ram/>
<location>A303</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>18</inv_id>
<owner>Dan Weeks</owner>
<device_name>watson</device_name>
<manufacturer>Apple</manufacturer>
<model>Mac mini</model>
<type>1</type>
<ip_address>192.168.0.18</ip_address>
<serial>C07KF0BVDWYN</serial>
<processor>Intel Core i7 2.3 GHz</processor>
<ram>4</ram>
<location>A303</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>19</inv_id>
<owner>Dan Weeks</owner>
<device_name>basepair</device_name>
<manufacturer>Apple</manufacturer>
<model>iMac</model>
<type>1</type>
<ip_address>192.168.0.19</ip_address>
<serial>D25GX0EMDHJV</serial>
<processor>Intel Core i5 2.7 GHz</processor>
<ram>16</ram>
<location>614</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>20</inv_id>
<owner>Dan Weeks</owner>
<device_name>HGEN-LT-Weeks</device_name>
<manufacturer>Apple</manufacturer>
<model>MacBook Air</model>
<type>2</type>
<ip_address>192.168.0.20</ip_address>
<serial>C02Q604GGFWL</serial>
<processor>Intel Core i7</processor>
<ram>8</ram>
<location>A300</location>
<type_id>2</type_id>
<type_desc>Laptop</type_desc>
</device>
<device>
<inv_id>21</inv_id>
<owner>David Finegold</owner>
<device_name>default</device_name>
<manufacturer>Apple</manufacturer>
<model>Mac Pro</model>
<type>1</type>
<ip_address>192.168.0.21</ip_address>
<serial>123456789</serial>
<processor>Intel Core i7 3.4 GHz</processor>
<ram>8</ram>
<location>A728</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>22</inv_id>
<owner>David Lassige</owner>
<device_name>hgen-david-193</device_name>
<manufacturer>Dell</manufacturer>
<model>OptiPlex 9010</model>
<type>1</type>
<ip_address>192.168.0.22</ip_address>
<serial>J21SQW1</serial>
<processor>Intel Core i7-3770 3.40GHz</processor>
<ram>16</ram>
<location>A307</location>
<type_id>1</type_id>
<type_desc>Workstation</type_desc>
</device>
<device>
<inv_id>23</inv_id>
<owner>Department</owner>
<device_name>HGEN-LT-Shared</device_name>
<manufacturer>Apple</manufacturer>
<model>MacBook Pro</model>
<type>2</type>
<ip_address>192.168.0.28</ip_address>
<serial>C02PXEDSFVH3</serial>
<processor>Inte Core i5</processor>
<ram>8</ram>
<location>A306</location>
<type_id>2</type_id>
<type_desc>Laptop</type_desc>
</device>
<device>
<inv_id>24</inv_id>
<owner>Department</owner>
<device_name>HGEN-DELL-Shared</device_name>
<manufacturer>Dell</manufacturer>
<model>Latitude E5450</model>
<type>2</type>
<ip_address>192.168.0.29</ip_address>
<serial>JG7Z062</serial>
<processor>Intel Core i5</processor>
<ram>8</ram>
<location>A300</location>
<type_id>2</type_id>
<type_desc>Laptop</type_desc>
</device>
<device>
<inv_id>25</inv_id>
<owner>Department</owner>
<device_name>hgenlab-color-8</device_name>
<manufacturer>HP</manufacturer>
<model>Color LaserJet CP3525</model>
<type>8</type>
<ip_address>192.168.0.24</ip_address>
<serial>JPCCC830LG</serial>
<processor/>
<ram/>
